### ISSUE TITLE
Definitie Areaalgegevens 

### ISSUE THREAD

**Issue by ElisabethDeVries** [bimloket/areaalgegevens-uitwisselen#1]
Areaalgegevens zijn: Gegevens over een boven- en/of ondergrondse ruimte dan wel gebouw, ook wel "Digital Twin" genoemd. Deze gegevens kunnen bestaan uit:

- geometrische gegevens 2D- of 3D; in een open bestandsformaat (bijvoorbeeld IFC, Open GIS)

- aan objecten gekoppelde gestructureerde data in een open bestandsformaat / gegevensformaat (bijvoorbeeld CSV, XML, linked data)

- niet-geometrische ongestructureerde data of documenten: foto's, bestanden in een niet-open dataformaat van één softwareleverancier

**Comment by NielsHoffmann** [comment]
Ik zou gegevenstype (geometrisch, administratief, 'ongestructureerd') loskoppelen van bestandsformaat. Een van de redenen dat wij het ESRI FileGeodatabase formaat zijn gaan gebruiken is nou juist het feit dat we daar geometrie EN administratieve data in een dataset bij elkaar kunnen uitwisselen. In de situatie daarvoor (bij ons shapefiles+excel) hadden we het probleem dat de bestanden vaker niet dan wel met elkaar overeen kwamen...

**Comment by NielsHoffmann** [comment]
mischien ook definitie areaalgegevens en doel uit elkaar trekken in lossen issues.

**Comment by nicoburgerhart** [comment]
In elk geval statische objectgegevens over ‘wat is het’, ‘wat kan het’ en ‘waar ligt het’.
Vraag: rekenen we (dynamische) sturingsdata zoals onderhoudsdata, storingsdata en toestandsinspecties van een object er wel of niet bij?

**Comment by ElisabethDeVries** [comment]
Lees hier waarom we het niet te complex moeten maken: https://www.rijksoverheid.nl/documenten/rapporten/2020/03/02/bijlage-1-definitief-bit-advies-programma-airbim

**Comment by redmer** [comment]
Voorstel tijdens bijeenkomst 1: Laten we het in deze werkgroep hebben over *statische assetdata* en niet dynamische gegevens.

**Comment by EricOosterom** [comment]
Eens, eerst concentreren op vaste object-en systeemgegevens. Van daaruit zijn (linked) koppelingen te maken naar dynamische datasets.

**Comment by CorneHelmons** [comment]
Is de scope hierbij de as-is situatie of trekken we het ook door naar ontwerp / revisie?

**Comment by nicoburgerhart** [comment]
Op termijn wil je wel een verschuiving van ongestructureerde data naar gestructureerde data

**Comment by ElisabethDeVries** [comment]
Dit moet worden opgepakt binnen het DSGO
