### ISSUE TITLE
Geometrie: Informatiemodel

### ISSUE THREAD

**Issue by ElisabethDeVries** [bimloket/areaalgegevens-uitwisselen#10]
Vraag aan deelnemers Gebruikersbijeenkomst 27 maart 2020:
Hoe vragen de opdrachtgevers de geometrie uit?
Hoe wordt het informatiemodel voor de geometrie voorgeschreven (objecttypes, NL-CS of anders: lagen/opmaak, detailniveau,...)
Hebben de opdrachtnemers hierbij wensen over afspraken, standaarden, handleidingen?

**Comment by nreyngou** [comment]
Wij vragen geometrie uit in GML formaat; één GML bestand per objecttype. We gebruiken hierbij  IMGeo als gevraagde geometrie.

**Comment by nicoburgerhart** [comment]
Is het bij COINS 20 niet per definitie GML?

**Comment by redmer** [comment]
Tijdens de bijeenkomst:

**Comment by jb19901234** [comment]
Aansluiten bij de internationale standaard. Dit niet willen regelen in COINS.

**Comment by NielsHoffmann** [comment]
geopackage staat tegenwoordig op de ptolu lijst...

**Comment by EricOosterom** [comment]
Je kent de GWSW ontologie, Elisabeth. Uitwisselen in GML, Geopackage kan vervolgens gewoon met NLCS stijlen/symbolen.

**Comment by CorneHelmons** [comment]
Meeste beheerders werken volgens mij nog in de basis met 2d objecten. Punten, lijnen en vlakken. Kan dus prima met GML / Geopackage. 
Gaan we over naar 3d informatie dan zou ik zeggen haak aan bij IFC ontwikkelingen

**Comment by Tim-VI** [comment]
Bij RWS en Provincie Gelderland hebben wij geometrie geleverd in GML formaat. Hierin hebben wij toen nog een keuze kunnen maken hoeveel GML's (gegroepeerd naar objecttype of KernGIS laag). Schiphol vraagt het in een coordinatenblok in IFC uit. ProRail lijkt het in IMX ook in GML te gaan vragen.

**Comment by nicoburgerhart** [comment]
Zie m.b.t. Rijkswaterstaat hoofdstuk 9 Geometrie in Instructie modelleren op basis van de OTL 2.4 http://publicaties.minienm.nl/documenten/instructie-modelleren-op-basis-van-de-otl-versie-2-4-gebruikershandleiding-bij-het-opbouwen-en-gebruiken-van-een-datamodel-voor-een-bim-projectdatabase-op-basis-van-de-otl-versie-2-3

**Comment by redmer** [comment]
Opmerkingen tijdens call: Hier bestaan verschillen tussen opdrachtgevers op dit moment. _ICDD Pt. 2_ definieert niet meer een grote ontologie die we vanuit COINS 2 kennen.

**Comment by ElisabethDeVries** [comment]
Als de conclusie is: gebruik de open uitwisselformaten die er zijn (GML, IFC) dan is de openstaande vraag: één object per bestandje, of alle objecten in één bestand, of een tussenweg?

**Comment by ElisabethDeVries** [comment]
> geopackage staat tegenwoordig op de ptolu lijst...

IFC staat ook op de [Pas-toe-of-leg-uitlijst](https://www.forumstandaardisatie.nl/open-standaarden/lijst/verplicht)

**Comment by ElisabethDeVries** [comment]
> Conclusie: Het informatiemodel voor geometrie moet zowel IFC als GML/Geopackage kunnen zijn. Opdrachtnemers krijgen met beide soorten te maken vanuit diverse opdrachtgevers.
> In ICDD part 1 wordt niet meer gedaan dan een pakketje met documenten linken en is dit dus beide mogelijk. Daar is ook een combi mogelijk: dat de objecten en in GML, en in IFC gerepresenteerd zijn.

**Comment by nreyngou** [comment]
Ik zou hier toch nog iets meer afspraken over willen maken. Als we kiezen voor GML, kiezen we dan voor:

- 1 grote GML file
- 1 GML file per object
- 1 GML file per objecttype

Geopackage ken ik niet, maar ik kan me voorstellen dat je ook daar een soortgelijke keuze moet maken. Door één keuze te maken maken we het leven van aannemers en softwarebouwers makkelijker denk ik :-).

**Comment by ElisabethDeVries** [comment]
Nou, daar het BIT rapport heel duidelijk heeft aangegeven dat de rekening moet houden met de applicaties waar de data moet worden ingelezen; &Schiphol en andere B&U opdrachtgevers daar IFC in moeten inlezen, en GWW opdrachtgevers juist GML gebruiken, moeten we bij de standaarden voor BIM loket met beide rekening houden. Is gezien de internationale waterscheidslijn Building SMART / OGS (?) ook nog steeds verdedigbaar

**Comment by nreyngou** [comment]
Ik heb het wat onhandig geformuleerd. We moeten zowel IFC als GML toestaan, maar bedoelde meer dat ALS GML dan voorgeschreven wordt in een ILS, ik vind dat we daar een standaardmanier voor moeten kiezen.

**Comment by ElisabethDeVries** [comment]
Dit issue moet worden opgepakt bij DSGO
