### ISSUE TITLE
Usecases COINS: Areaalgegevens uitwisselen

### ISSUE THREAD

**Issue by redmer** [bimloket/areaalgegevens-uitwisselen#11]
De wens van de gebruikersbijeenkomst d.d. 27 maart 2020 was voor het vervolg usecases (implementatiescenario's) uit te werken. 

Vragen / punten genoemd tijdens de bijeenkomst:

- Wat is het doel van de standaarden (COINS, ICDD, NTA 8035)?
- Wat valt hiervan onder ICDD, wat staat ons vrij(er)?
- Waar liggen de uitdagingen?
- Hou rekening met kleine usecases en niet alleen grote projecten. 
- Misschien niet eens een hele OTL te gebruiken, wellicht één objecttype uit te werken.

**Comment by nreyngou** [comment]
Bijvoorbeeld:

Als **opdrachtgever** wil ik gegevens over de aanwezige objecten  (geometrie, paspoortgegevens en technische dossiers) in een projectgebied en  de informatiebehoefte van de terug te leveren gegevens beschikbaar stellen  aan de **opdrachtnemer**  zodat ik de opdrachtnemer in staat stel de geactualiseerde  gegevens terug te leveren conform mijn informatiebehoefte.

**Comment by EricOosterom** [comment]
Voor een (liefst klein, concreet) project waarin (mede) ook riolering zit, met een echte opdrachtgever en echte opdrachtnemer, zouden we graag zo'n use case mee helpen vormgeven. Ons dataplatform mag daarvoor gebruikt worden. Beheersoftware i.c.m. onze (NTA conforme) GWSW ontologie en tooling geeft ons een basis waaruit gewerkt kan worden. Een combi met bijv. de Gelderland OTL en COINS/ICDD spreekt me aan.

**Comment by ElisabethDeVries** [comment]
Onderwerpen use case:
- De overheden zitten met een combi aan dataleveringen in hun maag. Daarom moet in een goede use case wijzigingen in de geometrie van het areaal voorkomen, zodat nieuwe gegevens aan de BGT moeten worden geleverd en in een beheersysteem ingelezen.

Om de schaalbaarheid te testen moet nagedacht worden over hoeveel objectypes / objecten in één uitiwsseling te combineren:
- Twee of meer objecttypes
- Meerdere instanties van elk objecttype
Voorbeeld van Gelderland, om bijvoorbeeld alle verkeerslichten in één levering te krijgen maar niet andere objecttypes erbij. Zorgt voor een kleiner datapakket, en je hebt minder deskundigen nodig om een dataset te toetsen.

**Comment by ElisabethDeVries** [comment]
Verwerk in: https://bimloket.github.io/areaalgegevens-uitwisselen/usecasegelderland/
