### ISSUE TITLE
Geometrie: Bestandsformaten

### ISSUE THREAD

**Issue by ElisabethDeVries** [bimloket/areaalgegevens-uitwisselen#2]
Vraag aan deelnemers Gebruikersbijeenkomst 27 maart 2020: 
Wordt een specifiek bestandsformaat voorgeschreven? 
Wordt de as-is geometrie ook zo aangeleverd?
~Beheerders van de openbare ruimte vragen van hun opdrachtnemers gegevens in GIS; ~gebouwbeheerders vragen meestal IFC.
Vindt gegevensverlies plaats, en zo ja, wat kan hieraan gedaan worden?
Hebben de opdrachtnemers hierbij wensen over afspraken, standaarden, handleidingen?

**Comment by nreyngou** [comment]
Belangrijk om hier aandacht te besteden aan zowel de levering(en) door opdrachtgever als de levering(en) door opdrachtnemer.

**Comment by nreyngou** [comment]
As-is geometrie wordt bij ons aangeleverd in een COINS 2.0 container. De geometrie heeft de vorm van GML bestanden, waarbij we nu hanteren dat elk objecttype een afzonderlijke GML file krijgt. Daarmee houd je het midden tussen één hele grote GML file en één file per object (dat worden er zoveel dat het onoverzichtelijk wordt).

**Comment by EricOosterom** [comment]
Via het Gegevenswoordenboek Stedelijk Water wisselen inmiddels alle relevante (riolerings)beheerpakketten via RDF/Turtle uit. Voor specifieke toepassingen worden vervolgens door tooling van Stichting RIONED geconverteerd naar CSV, XML, GML, Geopackage, en wat in de toekomst verder nog nodig zal zijn. Zo nodig zal COINS (3.0) of IFC omarmd worden, maar vooralsnog worden die in de rioleringssector niet gebruikt.

**Comment by ElisabethDeVries** [comment]
Dit moet worden opgepakt binnen het DSGO
