### ISSUE TITLE
Administratieve gegevens: Informatiemodel

### ISSUE THREAD

**Issue by ElisabethDeVries** [bimloket/areaalgegevens-uitwisselen#3]
Het informatiemodel voor administratieve gegevens wordt door asset managers op verschillende wijzen aangeleverd (te checken)
- Door gebouwbeheerders veelal in tabellen in de ILS (csv? Excel?)
- Door RWS, Gelderland(?) in linked data (OTL RWS)
- Door Noord-Holland: ?

Vraag aan deelnemers Gebruikersbijeenkomst 27 maart 2020: 
Hoe vragen de opdrachtgevers de administratieve gegevens uit? 
Worden de as-is gegevens ook zo aangeleverd?
Hoe wordt het informatiemodel voor de administratieve gegevens opgesteld / uitgewisseld 
Hebben de opdrachtnemers hierbij wensen over afspraken, standaarden, handleidingen?

**Comment by NielsHoffmann** [comment]
Het informatiemodel is bij ons expliciet NIET alleen administratief, maar definieert ook het geometrie deel. Interessanter is de vraag of het integrale model wat wij (Noord-Holland) hanteren (BGT+BOR) te groot en ingewikkeld is of niet. En hoe andere organisaties daar tegenaan kijken...

**Comment by sophiepfeiffer** [comment]
wat wordt bedoeld met administratieve data? misschien statische assetdata?

Over het algemeen (dus niet altijd) krijgen wij as-is in oude bestandsformaten en wordt aan de aannemer gedurende het project gevraagd dit op te werken en op de nieuwe manier terug te leveren. De betrouwbaarheid van de as-is is vaak een issue.

**Comment by nreyngou** [comment]
Wij leveren de OTL-Gelderland aan in COINS 2.0 formaat. Dit bevat de informatiebehoefte voor zowel geometrie als daaraan gekoppelde administratieve attributen.

**Comment by sophiepfeiffer** [comment]
> Het informatiemodel is bij ons expliciet NIET alleen administratief, maar definieert ook het geometrie deel. Interessanter is de vraag of het integrale model wat wij (Noord-Holland) hanteren (BGT+BOR) te groot en ingewikkeld is of niet. En hoe andere organisaties daar tegenaan kijken...

ik heb hierover navraag gedaan, ik heb begrepen dat de hoeveelheid informatie als veel en gedetailleerd wordt ervaren, het is veel werk, maar niet op een negatieve manier. het informatiemodel en de levering zelf zijn juist helder en eenvoudiger dan bij veel andere opdrachtgever

**Comment by nreyngou** [comment]
Wij hebben nog een eigen informatiemodel. Maar willen ook toe naar OTL op basis van IMBOR. Wel met eigen Gelderlandspecifieke uitbreidingen en selecties.

**Comment by sophiepfeiffer** [comment]
Belangrijk is in alle gevallen, dat de informatievraag van OG compleet en expliciet is. Daarnaast een standaardformaat voor uitwisseling.

**Comment by EricOosterom** [comment]
Het GWSW-ontologie definieert zowel de administratieve data, geometrie als topologie. Daar kunnen de (riolerings)beheerpakketten goed mee uit de voeten. Er is al een gemeente die een CDE aan het bouwen is op basis van een triplestore, in eerste instantie voor riolering en ook andere domeinen.

**Comment by EricOosterom** [comment]
Zoals Jasper zegt, er is wel dringend behoefte aan meer/betere/generieke tooling en opschaling. De potentie is er! Voor RIONED is dat als ontologie-beheerder zelf ook heel belangrijk om betere, meer generieke LD-tooling te krijgen. Graag zouden we dat met andere partijen verkennen en organiseren....

**Comment by ElisabethDeVries** [comment]
Het hoeft niet meteen linked data te zijn... we kunnen ook als standaard zeggen dat de vraag om x eigenschappen bij een object op te leveren ook gesteld kan worden in, bij wijze van spreken, CSV formaat. Alleen moet je dan aparte tabellen sturen als je waardelijsten wil gebruiken (als in, antwoord a b en c zijn geaccepteerde antwoorden

**Comment by ElisabethDeVries** [comment]
Dit moet worden opgepakt binnen het DSGO
