### ISSUE TITLE
Doel uitwisselen areaalgegevens

### ISSUE THREAD

**Issue by ElisabethDeVries** [bimloket/areaalgegevens-uitwisselen#4]
De areaalgegevens worden uitgewisseld tussen twee partijen, die:

-  of elk een eigen "Digital Twin" onderhouden;

- of een gezamenlijke projectomgeving ("Common Data Environment" uit ISO 19650). 

In beide gevallen wordt informatie over veranderingen in de areaalgegevens uitgewisseld zodat de Digital Twin up to date blijft.

**Comment by sophiepfeiffer** [comment]
Ik zou nog weg blijven van de term 'digital twin' voor dit overleg, maar de focus leggen op statische assetdata.
Ik ben van mening dat iedere partij in zijn eigen omgeving/systeem moet kunnen werken conform zijn eigen processen, aangezien de core-business en dus bedrijfsproces van een aannemer anders is dan van een opdrachtgever en deze ook onderling kunnen verschillen. Maar we moeten afspraken maken over de uitwisseling van data.

**Comment by EricOosterom** [comment]
Eens met Sophie: Hoe partijen intern zaken organiseren, modelleren en registreren is eigenlijk niet zo relevant, hoe en wat uitgewisseld/ontsloten wordt WEL. De focus van standaarden zoals IMBOR, GWSW, Aquo enzovoort zou moeten liggen op uitwisseling (wat, hoe).

Ook voor mij is Digital Twin of CDE nog wat ver weg. Maar in projecten (zoals aanleg, inspectie of beheer van een weg/riool/brug/….) betekent dat data van asset manager naar bijv. contractpartij zal moeten gaan en tijdens en na het project weer teruggeleverd. Areaaldata is voor ons dus in eerste instantie vaste data (ligging, kenmerken) en wellicht ook toestands-/conditiedata.

**Comment by sophiepfeiffer** [comment]
het hangt ook van de fase af. in de ontwerpfase wissel je andere data met elkaar uit en op een andere wijze, samenwerken in een CDE logischer. Bij oplevering of in B&O is data overdragen logischer.

**Comment by redmer** [comment]
Tijdens de bijeenkomst: 

Verschillende fases van het bouwwerk (ontwerp, bouw, beheer en onderhoud) hebben verschillende informatiebehoeftes. 

Niet besloten of ons doel voor alle fases geldt, maar in elk geval: de statische beheergegevens die de assetmanager nodig heeft. 

Bij de vorige gebruikersbijeenkomst van COINS 3: er is al besloten voor areaalgegevens uitwisselen (contracten als data, en inspectiegegevens: dat zijn andere werkgroepen ➡ buiten scope deze repo)

**Comment by ElisabethDeVries** [comment]
Doel is beschreven in https://bimloket.github.io/areaalgegevens-uitwisselen/usecasegelderland/
