### ISSUE TITLE
Administratieve gegevens: Bestandsformaten

### ISSUE THREAD

**Issue by ElisabethDeVries** [bimloket/areaalgegevens-uitwisselen#5]
In welke bestandsformaten worden administratieve gegevens nu opgevraagd? Willen de gebruikers dit standaardiseren, of hier regels of handleidingen voor opstellen?

Bijvoorbeeld 
Schiphol: Geometrie + Administratief in IFC met XML berichten
RWS: COINS containers met Geometrie (formaat?), Administratief (linked data) en documenten

**Comment by nreyngou** [comment]
We vragen de administratieve gegevens uit in COINS 2.0 formaat.

**Comment by EricOosterom** [comment]
Zoals gezegd, GWSW biedt rioleringsdata als BIM in RDF/Turtle vanuit beheersoftware, die doorgezet kan worden naar andere bestandsformaten.

**Comment by redmer** [comment]
Opgemerkt werd: opdrachtgevers maken verschillende keuzes, omdat de tooling er nauwelijks is cq. korte levens zijn beschoren. Weinig ondersteuning van grote softwareleveranciers voor triplestores en Linked Data. In tegenstelling tot IFC.

**Comment by ElisabethDeVries** [comment]
Dit issue moet worden opgepakt bij het DSGO
