### ISSUE TITLE
Koppelen van foto's, documenten

### ISSUE THREAD

**Issue by ElisabethDeVries** [bimloket/areaalgegevens-uitwisselen#6]
Wat wordt door verschillende opdrachtgevers nu gevraagd bij het leveren van areaalgegevens? Hoe wordt een foto of ander document aan een object gekoppeld? Willen de gebruikers hier regels / handleidingen bij hebben? Zijn er landelijke afspraken nodig, of afspraken per objecttype of …?

**Comment by nreyngou** [comment]
We vragen opdrachtnemers om documenten te koppelen in de objectenboom in de COINS 2.0 containers. We hebben een aparte lijst van opgevraagde documenten, waarbij we specificeren aan welk objecttype uit de OTL dat document gekoppeld moet worden. Dat leveren we mee als bijlage aan de ILS.

**Comment by sophiepfeiffer** [comment]
een document kun je koppelen aan een object (liefst aan een object, geen bijzondere constructies aub) d.m.v. een link naar het bestand in een ander systeem of door het bestand mee te leveren in COINS. de vraag is of je dat laatste moet willen, we lopen dan vaak tegen de bestandsgrootte van de levering aan, vooral voor de ontvanger. 
let ook op kardinaliteit (niet teveel doen) en té specifieke documenttypes, de eindgebruikers moeten er ook mee kunnen werken

**Comment by ElisabethDeVries** [comment]
Dit issue moet worden opgepakt bij het DSGO
