### ISSUE TITLE
Informatie-leveringsspecificatie (ILS) van areaalgegevens

### ISSUE THREAD

**Issue by ElisabethDeVries** [bimloket/areaalgegevens-uitwisselen#7]
Mogelijk dubbel met vraag bij "Contract als data" 

Hoe vragen de opdrachtgevers nu informatieleveringen uit op het gebied van areaalgegevens? Hebben opdrachtnemers hier wensen over, valt er te standaardiseren, moet de vraag als data beschikbaar komen in plaats van de lappen tekst, …?

**Comment by nreyngou** [comment]
![ILS'en](https://user-images.githubusercontent.com/35819506/77339221-bf604480-6d2b-11ea-8d2f-e086c32390ec.png)
A = Opdrachtgever
B = Opdrachtnemer
C = Leverancier

Wellicht goed om toe te voegen dat het gaat om de ILS die de informatiebehoefte vanuit opdrachtgever naar opdrachtnemer specificeert (t1 in het bijgesloten plaatje). Dit voorkomt verwarring met bijvoorbeeld de BIM Basis ILS (die juist gaat over ILS'en tussen opdrachtnemers of tussen een opdrachtnemer en leveranciers).

**Comment by sophiepfeiffer** [comment]
Vaak zijn het inderdaad lappen tekst en is het niet eenduidig hoe en wat er geleverd dient te worden. Ik pleit altijd voor een duidelijke specificatie of een voorbeeldlevering om contractuele discussies te voorkomen. Indien dit nog niet bekend is dan lijkt het mij goed om al vooraf aan te geven dat het om een gezamenlijk ontwikkeltraject gaat en hier in een tender al duidelijk over te zijn naar elkaar.

**Comment by EricOosterom** [comment]
Vanuit het GWSW zouden we graag de combi maken tussen areaaldata aan onze kant en bijvoorbeeld de contractdata-ontologie van CROW om tot (standaard)contracten te komen. 

In het GWSW zijn overigens enkele uitwisselformaten gedefinieerd en gemodelleerd, inclusief minimale datasets en kwaliteitseisen waartegen gevalideerd kan worden. Wij hebben nog geen ILS, mede omdat een ILS alleen voor riolering niet echt zinvol lijkt. Liever een combi voor heel BOR bij gemeenten/waterschappen.

**Comment by nreyngou** [comment]
Laat de OTL over de semantiek gaan, het gegevensmodel (gevraagde objecten, eigenschappen, relaties, waardenlijsten, etc..)  en de ILS over allerlei afspraken daar omheen (bestandsformaten, levermomenten e.d.).

**Comment by nreyngou** [comment]
Schrijf de ILS zoveel mogelijk als 'eisen' op en zo min mogelijk als verhaal.

**Comment by redmer** [comment]
Opmerkingen tijdens call: OTL, ILS en uitwisselingsformaat zijn nu sterk verwoven. Dat maakt het lastig voor opdrachtnemers om te weten waar wat staat. @NielsHoffmann merkt op dat vanuit de interprovenciale ontwikkeling een gezamenlijke ILS te maken, de informatiespecificatie in de OTL wordt gehouden en de ILS gaat over het proces en de formaten.

**Comment by ElisabethDeVries** [comment]
Dit issue moet worden opgepakt bij het DSGO en de ILS-configurator
