### ISSUE TITLE
Informatiemodel metadata bij documenten

### ISSUE THREAD

**Issue by ElisabethDeVries** [bimloket/areaalgegevens-uitwisselen#8]
Vragen de opdrachtgevers om metadata bij documenten?
Hoe wordt dit informatiemodel aangeboden?
Wordt er ook een bestandsformaat voorgeschreven?
Hebben opdrachtnemers hier behoefte aan afspraken, standaardisatie, handleidingen?

**Comment by sophiepfeiffer** [comment]
Vaak wordt in een ILS beschreven hoe wij bestanden moeten aanleveren aan de opdrachtgever. Bij sommige opdrachtgevers wordt er ook een (soms zeer uitgebreide) lijst met metadata gevraagd, hier ontbreekt wat mij betreft de verwijzing naar een norm, wij zullen altijd een mapping met onze 'eigen' metadata moeten maken.
Daarnaast en soms tegelijk zijn er nog veel opdrachtgevers die vragen om documenten op te leveren in een voorgeschreven mappenstructuur, met bestandsnamen die opgebouwd zijn uit metadata-velden. Wij moeten dan vanuit ons DMS eigenlijk 'downgraden' naar de wens van de opdrachtgever.

**Comment by redmer** [comment]
Samenvatting uit call: Eisen aan documenten hoort ook bij de OTL, Noord-Holland benoemt de vereisten vanuit de Archiefwet ➡ Toepassingsprofiel Metadatering Lokale Overheden (TMLO).

**Comment by ElisabethDeVries** [comment]
Dit issue moet worden opgepakt bij het DSGO
